package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;

public class FoodViewController implements Initializable {
	@FXML
	private TableView<ModelTable> FoodTable;
	@FXML
	private TableColumn<ModelTable, String> Food;
	@FXML
	private Button AddBtn;

	ObservableList<ModelTable> oblist = FXCollections.observableArrayList();

	// Event Listener on Button.onAction
	@FXML
	public void ranClicked(ActionEvent event) {
		// TODO Autogenerated
		JOptionPane.showMessageDialog(null, oblist.get((int) (Math.random() * oblist.size())).getFood() + " 당첨!");
	}

	@FXML
	void btn_AddClicked1(ActionEvent event) {
		Stage addStage = new Stage();
		Stage primaryStage = (Stage)AddBtn.getScene().getWindow();
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("AddFoodView.fxml"));
			Scene scene = new Scene(root);
			addStage.setTitle("식당 추가");
			addStage.setScene(scene);
			addStage.show();
			primaryStage.close();
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

		Connection conn = DBConnection.getConnection(); // 만들어둔 DBconnection 클래스에서 데이터베이스 연결을 불러옵니다.
		try {
			ResultSet rs = conn.createStatement().executeQuery("select * from FOOD"); // 쿼리문을 작성하는 곳입니다.

			while (rs.next()) {
				oblist.add(new ModelTable(rs.getString("food")));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
			try {
				conn.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

		Food.setCellValueFactory(new PropertyValueFactory<>("food"));

		FoodTable.setItems(oblist);

	}
}
