package Controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;

import application.DBConnection;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginViewController {
	@FXML
	private TextField ip_ID;
	@FXML
	private PasswordField ip_PW;
	@FXML
	private Button lgn_Btn;
	@FXML
	private Button reg_Btn;

	// Event Listener on Button[#lgn_Btn].onAction
	@FXML
	public void lgn_Clicked(ActionEvent event) {
		// TODO Autogenerated
String PWfromDB = members_load(ip_ID.getText());
		
		try {
			if(PWfromDB.equals(ip_PW.getText())&&PWfromDB!="") {
				JOptionPane.showMessageDialog(null, "로그인 성공");
				Stage loginStage = (Stage) lgn_Btn.getScene().getWindow();
				Stage foodStage = new Stage();
				Parent root;
				root = FXMLLoader.load(getClass().getResource("/View/FoodView.fxml"));

				Scene scene = new Scene(root);

				foodStage.setTitle("오늘의 식당");
				foodStage.setScene(scene);
				foodStage.show();

				loginStage.close();
			}
			else {
				JOptionPane.showMessageDialog(null, "로그인 실패, 아이디 또는 비빌번호가 틀렸습니다.");
			}
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#reg_Btn].onAction
	@FXML
	public void reg_Clicked(ActionEvent event) {
		// TODO Autogenerated
		try {
				Stage loginStage = (Stage) lgn_Btn.getScene().getWindow();
				Stage registStage = new Stage();
				Parent root;
				root = FXMLLoader.load(getClass().getResource("/View/RegistView.fxml"));

				Scene scene = new Scene(root);

				registStage.setTitle("회원가입");
				registStage.setScene(scene);
				registStage.show();

				loginStage.close();
		} catch(Exception e) {
			e.printStackTrace();
		}
		
	}
	
	public static String members_load(String id) {
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		String pw = "";
		
		try {
			conn = DBConnection.getConnection();
			stmt = conn.createStatement();
			
			String sql = "SELECT pw FROM TEST1 WHERE id = "+"'"+id+"'";
			rs = stmt.executeQuery(sql);
			
			while(rs.next()) {
				pw = rs.getString(1);
			}
			
		} catch(Exception e) {
			e.printStackTrace();
		}
		finally {
			try {
				if(conn != null && !conn.isClosed()) {
					conn.close();
				}
				if(stmt != null && stmt.isClosed()) {
					stmt.close();
				}
			} catch(Exception e) {
				e.printStackTrace();
			}
		}
		return pw;
	}
}

