package Controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginViewController {
	@FXML
	private TextField ip_ID;
	@FXML
	private PasswordField ip_PW;
	@FXML
	private Button lgn_Btn;
	@FXML
	private Button reg_Btn;

	// Event Listener on Button[#lgn_Btn].onAction
	@FXML
	public void lgn_Clicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#reg_Btn].onAction
	@FXML
	public void reg_Clicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
